version: '3.8'

services:
  db:
    container_name: linh_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'laptop2'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password-admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
    networks:
      - cine-network

  redis:
    container_name: redis-container
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - cine-network

  be-service:
    container_name: cinego-be-container
    build: ./cine_be
    restart: always
    environment:
      DATABASE_URL: jdbc:mysql://linh_db:3306/laptop2
      DATABASE_USERNAME: username
      DATABASE_PASSWORD: password
      SERVER_PORT: 9595
      REDIS_HOST: redis-container
    ports:
      - '9595:9595'
    depends_on:
      - db
      - redis
    networks:
      - cine-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - cine-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - cine-network

  mongodb:
    image: mongo:6.0
    container_name: cinego-mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - cine-network

  fe-service:
    container_name: cinego-fe-container
    restart: unless-stopped
    build: ./cine-fe
    ports:
      - '180:80'
    networks:
      - cine_network

networks:
  cine-network:
    driver: bridge
