name: Java CI - Cinego Ticket

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/maven/plugins
            !~/.m2/repository/org/codehaus/mojo
          key: ${{ runner.os }}-maven-${{ hashFiles('**/cine-be/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Grant execute permissions for mvnw
        run: chmod +x ./cine-be/mvnw

      - name: Run Unit Tests with Maven Wrapper (Debug)
        run: ./mvnw -X -e test
        working-directory: ./cine-be
